# $HOME/.config/alacritty/alacritty.toml
# Emanuele, 2025-08-01

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.7
blur = true
dynamic_title = true
decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 200
lines = 60

[font]
size = 13.0

[font.normal]
family = "TX-02"
style = "Retina"

[font.italic]
family = "TX-02"
style = "Italic"

[font.bold]
family = "TX-02"
style = "Bold"

[font.bold_italic]
family = "TX-02"
style = "Bold Italic"

[cursor]
thickness = 0.15
blink_timeout = 0

[cursor.style]
shape = "Beam"
blinking = "Always"

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
working_directory = "Development"
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
